### ISSUE TITLE
Projekt umbenennen? -> EN

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/redaxo-entwickler.github.io#10]
Wir wollen REDAXO ja für nicht-deutschsprachige Nutzer öffnen, verwenden hier aber einen deutschsprachigen Projektnamen, der mit einer deutschsprachigen Domain verknüpft werden wird. Irgendwie ungeschickt, denn gerade _dieses_ Projekt in seiner Funktion als Weltkarte für REDAXO-Entwickelnde sollte doch englischsprachig aufgezogen werden!

Wollen wir das Projekt also nicht lieber in `redaxo-developers.github.io` umbennen? Und später auch die passende Domain registrieren? Wobei eigentlich auch die github.io-Domain als Haupt-URL verwendet werden könnte, finde ich. Denn jetzt, wo sich das Projekt von einem Dienstleisterverzeichnis inzwischen zu einer reinen Developer-Map entwickelt hat, die zudem bei GitHub gepflegt wird, könnten wir auch gut einfach nur die GitHub-Domain nehmen, oder?

--
**Update:** `redaxo-community.github.io`? Siehe Diskussion unten.

**Comment by staabm** [comment]
👍

**Comment by lexplatt** [comment]
👍🏼

**Comment by alexplusde** [comment]
> Denn jetzt, wo sich das Projekt von einem Dienstleisterverzeichnis inzwischen zu einer reinen Developer-Map entwickelt hat...

Das, finde ich, ist die verkehrte Richtung. Die REDAXO-Community fußt auch auf vielen kleinen Agenturen, die gerade Schritt für Schritt ausgegrenzt werden. Dabei haben die REDAXO auch groß gemacht, bzw. sind weiter eine Zielgruppe für neue Mitstreiter der Community. Mit solchen Richtungsänderungen (Fokus rein auf Entwickler, Programmierer - weniger Gestalter, Freelancer, Allrounder etc.) sehe bspw. ich mich nicht mehr von **diesem** Projekt angesprochen.

Zur eigentlichen Frage: Sehr gerne mehrsprachig, da REDAXO ja bspw. im Backend den Schritt gerade vollzieht. Mit meinem Prolog hier würde ich lieber world-of-redaxo.github.io, made-with-redaxo.github.io, o.ä. sehen, sodass die Karte sowohl Entwickler, als auch Agenturen/Freelancer, als auch fertige Projekte zeigt.

**Comment by schuer** [comment]
redaxo-community.github.io

Alex hat recht: Es soll für alle sein, die mit REDAXO zu tun haben, nicht nur Developer. Aber ich würde keine Firmen reinnehmen, sondern nur die Leute innerhalb dieser Firmen. Und keine Projekte/Referenzen.
Für Firmen und Referenzen gibt es MyREDAXO.

**Comment by staabm** [comment]
Vllt brauchen wir nen besseren begriff als „entwickler“. Prinzipiell wollen wir jeden ansprechen, nicht nur entwickler/programmierer

**Comment by staabm** [comment]
Einfach nur „community map“?

**Comment by skerbis** [comment]
Warum keine Firmen? Ich bin zwar hier als Person aktiv. Aufträge nehme ich / wir nur als Unternehmen an.

**Comment by schuer** [comment]
Diskussion hier beachten: https://github.com/FriendsOfREDAXO/redaxo-entwickler.github.io/issues/2#issuecomment-335155673

**Comment by skerbis** [comment]
Ok, jetzt ist es klarer

**Comment by schuer** [comment]
Sorry, ich war gestern unterwegs und konnte mobil nur wenig tippen. Jetzt nochmal ausführlicher:

`redaxo-developers.github.io` ist leider wirklich zu einseitig. In der anderen Diskussion, die ich verlinkt habe, wird es etwas deutlicher: Wir sollten eine Karte schaffen, in der _jede Person_ ein Fähnchen setzen kann, die in _irgendeiner Weise_ mit REDAXO zu tun hat. Es geht vor allem darum, zu visualisieren, wo sich die REDAXO-Community befindet. Deshalb wäre der Name vielleicht auch sehr passend: `redaxo-community.github.io`.

Und es geht dabei wirklich um jede einzelne Person, nicht um eventuelle Dienstleister dahinter. Jede Person innerhalb eines Dienstleister-Teams kann und soll sich eintragen, und sie kann dabei natürlich kenntlich machen, dass sie dem Dienstleister-Team angehört. Aber es soll keine Dienstleister-Karte sein, sondern eine Community-Karte. Dienstleister können sich stattdessen mit ihren Referenzen in MyREDAXO auf redaxo.org eintragen.

Wäre das so in eurem Interesse? (Speziell auch @alexplusde?)
Und wenn ja, was wäre ein geeigneter Name? `redaxo-community.github.io`?

**Comment by schuer** [comment]
Danke für euer Feedback. Dann machen wir es jetzt einfach mal so, und sollte jemand doch noch Einwände oder eine bessere Idee haben, macht einfach das Issue wieder auf.

**Comment by schuer** [comment]
Nachtrag: Ich habe verpasst, dass nur GitHub-Organisationen schöne URLs im Stil von https://friendsofredaxo.github.io bekommen. Repos innerhalb einer Organisation — so wie dieses jetzt — erhalten eine Unterseite mit ihrem Namen. Deshalb habe ich das Repo nun schlicht in `community` umbenannt, so dass unsere URL lautet:

https://friendsofredaxo.github.io/community/

Hoffe, das ist in eurem Sinn. Wir können natürlich trotzdem noch eine eigene Domain registrieren, wenn wir wollen, so wie aktuell redaxo-entwickler.de.
